// src/services/mockData.ts
import { Task, Column, TaskStatus } from '../types/task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Implementar sistema de login',
    description: 'Criar autenticação JWT com refresh tokens e validação de permissões',
    status: 'completed',
    responsible: { name: 'João Silva', email: 'joao@email.com' },
    createdAt: new Date('2025-01-10'),
    completedAt: new Date('2025-01-15'),
    dueDate: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: '2',
    title: 'Design responsivo do dashboard',
    description: 'Desenvolver layout adaptativo para mobile, tablet e desktop',
    status: 'in_progress',
    responsible: { name: 'Maria Santos', email: 'maria@email.com' },
    createdAt: new Date('2025-12-12'),
    dueDate: new Date('2025-12-19'),
    updatedAt: new Date('2025-12-12'),
  },
  {
    id: '3',
    title: 'Testes unitários e integração',
    description: 'Implementar testes para componentes principais e lógica de negócio',
    status: 'todo',
    responsible: { name: 'Carlos Oliveira', email: 'carlos@email.com' },
    createdAt: new Date('2025-12-15'),
    dueDate: new Date('2025-12-30'),
    updatedAt: new Date('2025-12-15'),
  },
  {
    id: '4',
    title: 'Documentação da API REST',
    description: 'Escrever documentação Swagger/OpenAPI para endpoints existentes',
    status: 'overdue',
    responsible: { name: 'Ana Costa', email: 'ana@email.com' },
    createdAt: new Date('2025-01-05'),
    dueDate: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-11'),
  },
  {
    id: '5',
    title: 'Otimização de performance',
    description: 'Melhorar tempo de carregamento com lazy loading e code splitting',
    status: 'todo',
    responsible: { name: 'Pedro Almeida', email: 'pedro@email.com' },
    createdAt: new Date('2025-01-18'),
    dueDate: new Date('2025-02-05'),
    updatedAt: new Date('2025-01-18'),
  },
  {
    id: '6',
    title: 'Implementar filtros avançados',
    description: 'Adicionar filtros por data, prioridade e múltiplos responsáveis',
    status: 'in_progress',
    responsible: { name: 'Juliana Lima', email: 'juliana@email.com' },
    createdAt: new Date('2025-12-02'),
    dueDate: new Date('2025-12-05'),
    updatedAt: new Date('2025-12-02'),
  },
  {
    id: '7',
    title: 'Integração com calendário',
    description: 'Sincronizar tarefas com Google Calendar e Outlook',
    status: 'todo',
    responsible: { name: 'Roberto Santos', email: 'roberto@email.com' },
    createdAt: new Date('2025-01-22'),
    dueDate: new Date('2025-02-28'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: '8',
    title: 'Relatórios de produtividade',
    description: 'Gerar relatórios semanais e mensais de conclusão de tarefas',
    status: 'completed',
    responsible: { name: 'Camila Rodrigues', email: 'camila@email.com' },
    createdAt: new Date('2025-01-08'),
    completedAt: new Date('2025-01-14'),
    dueDate: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-14'),
  },
];

export const mockColumns: Column[] = [
  {
    id: 'todo',
    title: 'A Fazer',
    tasks: mockTasks.filter(task => task.status === 'todo'),
    wipLimit: 5,
    color: '#3B82F6',
  },
  {
    id: 'in_progress',
    title: 'Em Progresso',
    tasks: mockTasks.filter(task => task.status === 'in_progress'),
    wipLimit: 3,
    color: '#F59E0B',
  },
  {
    id: 'overdue',
    title: 'Atrasado',
    tasks: mockTasks.filter(task => task.status === 'overdue'),
    color: '#EF4444',
  },
  {
    id: 'completed',
    title: 'Concluído',
    tasks: mockTasks.filter(task => task.status === 'completed'),
    color: '#10B981',
  },
];