// src/config/icons.ts
import { 
  faBars, 
  faSignOutAlt, 
  faUser, 
  faCog, 
  faPlus, 
  faChartBar, 
  faColumns,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendarAlt,
  faUser as faUserIcon,
  faCheckCircle,
  faExclamationTriangle,
  faClock,
  faTasks,
  faCheckSquare,
  faArrowUp,
  faArrowDown,
  faTrash,
  faEdit,
  faEye,
  faEyeSlash,
  faLock,
  faEnvelope,
  faKey,
  faHome,
  faBell,
  faCrown,
  faUsers,
  faMobileAlt,
  faShieldAlt,
  faRocket,
  faArrowLeft,
  faSpinner
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  menu: faBars,
  logout: faSignOutAlt,
  profile: faUser,
  settings: faCog,
  add: faPlus,
  dashboard: faChartBar,
  kanban: faColumns,
  search: faSearch,
  filter: faFilter,
  sort: faSort,
  sortUp: faSortUp,
  sortDown: faSortDown,
  calendar: faCalendarAlt,
  user: faUserIcon,
  check: faCheckCircle,
  warning: faExclamationTriangle,
  clock: faClock,
  tasks: faTasks,
  checkbox: faCheckSquare,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  trash: faTrash,
  edit: faEdit,
  eye: faEye,
  eyeSlash: faEyeSlash,
  lock: faLock,
  email: faEnvelope,
  key: faKey,
  home: faHome,
  bell: faBell,
  crown: faCrown,
  users: faUsers,
  mobile: faMobileAlt,
  shield: faShieldAlt,
  rocket: faRocket,
  arrowLeft: faArrowLeft,
  spinner: faSpinner
};

export type IconName = keyof typeof icons;